site_name: 四川大学生命科学课程攻略
repo_url: https://github.com/SCUBioGuide/SCUBioGuide
docs_dir: .

theme:
  name: readthedocs
  highlightjs: true

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - def_list
  - toc:
      permalink: "#"

plugins:
  - search
  - same-dir
